name: CI Pipeline with Docker

# Ejecutar el pipeline en eventos específicos
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

# Definir los trabajos (jobs) a realizar
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 5. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        run: docker login -p "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6. Construir y subir la imagen Docker a Docker Hub
      - name: Build Docker Image
        run: docker build -t fernandaglez/apigeo:${{github.sha}} .

      - name: Tag Latest
        run: docker tag fernandaglez/apigeo:${{ github.sha }} fernandaglez/apigeo:latest

      - name: Push Docker Image
        run: |
          docker push fernandaglez/apigeo:${{ github.sha }}
          docker push fernandaglez/apigeo:latest

        